[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'

# 5667: Unused function parameter. Remove or comment out the variable name to silence this warning.
# 5740: Unreachable code.
ignored_error_codes = [5667, 5740]
# setting this to allow expensive larger inserts during tests
memory_limit = 100_000_000
